## 10장. 예외처리

### 10.1 코루틴에서 예외

* 예외가 발생하면, 코루틴 빌더는 부모도 취소시키고, 취소된 부모는 자식들 모두를 취소시킨다.
```kotlin
import kotlinx.coroutines.*

suspend fun main(): Unit = coroutineScope {
  launch {
    launch {
      delay(1000)
      throw Error("some error")
    }

    launch {
      delay(2000)
      println("will not be printed")
    }

    launch {
      delay(500)
      println("will be printed")
    }
  }

  launch {
    delay(2000)
    println("will not be printed")
  }
}
```

### 10.2 코루틴 종료 멈추기

* 코루틴간 상호 작용은 잡을 통해서 이루어 지기 때문에, 새로운 코루틴 빌더를 try/catch로 감싸는 것은 작동하지 않는다.
```kotlin
import kotlinx.coroutines.*

suspend fun main(): Unit = coroutineScope {
    // 코루틴 빌더를 try/catch 로 감싸도 무시된다.
    try {
        launch {
            delay(1000)
            throw Error("some error")
        }
    } catch(e: Throwable) {
        println("will not be printed")
    }

    launch {
        delay(2000)
        println("will not be printed")
    }
}
```

### 10.3 SupervisorJob 사용하기

* `SupervisorJob`을 사용하면 자식에서 발생한 예외를 무시할 수 있다.
* SupervisorJob을 통해 scope을 생성하고, 해당 scope에서 자식 코루틴을 실행한다.
```kotlin
suspend fun main(): Unit = coroutineScope {
    val scope = CoroutineScope(SupervisorJob())
    scope.launch {
        delay(1000)
        throw Error("some error")
    }

    scope.launch {
        delay(2000)
        println("will be printed")
    }

    scope.coroutineContext.job.children.forEach { it.join() }
}
```
* SupervisorJob을 자식 코루틴에게 전달하면, 자식 코루틴의 예외가 무시된다.
```kotlin
import kotlinx.coroutines.*

suspend fun main(): Unit = coroutineScope {
    val job = SupervisorJob()
    launch(job) {
        delay(1000)
        throw Error("some error")
    }

    launch(job) {
        delay(2000)
        println("will be printed")
    }

    job.complete()
    job.join()
}
```

### 10.4 SupervisorScope 사용하기

* 예외 전파를 막는 또다른 방법은 `SupervisorScope`를 사용하는 것이다.
```kotlin
import kotlinx.coroutines.*

suspend fun main(): Unit = coroutineScope {
    supervisorScope {
        launch {
            delay(1000)
            throw Error("some error")
        }

        launch {
            delay(2000)
            println("will be printed")
        }
    }

    coroutineContext.job.children.forEach { it.join() }
    println("done")
}
```

### 10.5 await

* async 빌더 역시 supervisorJob or supervisorScope를 사용하면 예외 전파를 막을 수 있다.
* 하지만 await를 호출하면 예외가 발생하여 반환할 값이 없지만, MyException을 던진다.
```kotlin
import kotlinx.coroutines.*

class MyException: Throwable()
suspend fun main(): Unit = supervisorScope {
    val str1 = async<String> {
        delay(1000)
        throw MyException()
    }

    val str2 = async {
        delay(2000)
        "world"
    }

    try {
        println(str1.await()) // MyException 발생
    } catch(e: Throwable) {
        println(e)
    }

    println(str2.await())

    coroutineContext.job.children.forEach { it.join() }
}
```

### 10.6 CancellationException은 부모까지 전파되지 않는다.

* CancellationException의 서브 클래스라면 부모로 전파되지 않는다.
* 단지 현재의 코루틴과 자식 코루틴만 취소한다.
```kotlin
import kotlinx.coroutines.*

class MyNonPropagationException: CancellationException()
suspend fun main(): Unit = coroutineScope {
    launch {
        launch {
            delay(1000)
            println("will not be printed")
        }

        throw MyNonPropagationException()
    }

    launch {
        delay(2000)
        println("will be printed")
    }

    coroutineContext.job.children.forEach { it.join() }
    println("done")
}
```

### 10.7 코루틴 예외 핸들러

* 예외가 발생했을때 해야 하는 행위가 있다면 `CoroutineExceptionHandler`를 사용하면 된다.
* 예외 전파를 막지는 않지만, 예외 발생시 해당 블럭이 실행된다. 
```kotlin
import kotlinx.coroutines.*

suspend fun main(): Unit = coroutineScope {
    val handler = CoroutineExceptionHandler { ctx, throwable ->
        println("Caught $throwable")
    }

    val scope = CoroutineScope(SupervisorJob() + handler)

    scope.launch {
        delay(1000)
        throw Error("some error")
    }

    scope.launch {
        delay(2000)
        println("will be printed")
    }

    scope.coroutineContext.job.children.forEach { it.join() }
    println("done")
}
```